name: PR Slack Notification

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR Details to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: "SBNRI PR Bot"
          SLACK_TITLE: "New PR in Backend ðŸš€"
          SLACK_MESSAGE: |
            *PR Title:* ${{ github.event.pull_request.title }}
            *Author:* ${{ github.event.pull_request.user.login }}
            *Link:* ${{ github.event.pull_request.html_url }}
            *Branch:* ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }}
            *Action Required:* A QA Engineer needs to review the diff and map the required test cases.
          SLACK_COLOR: "good"
          MSG_MINIMAL: true
